### ISSUE TITLE
Fault injection API enhacements

### ISSUE THREAD

**Issue by pablochacin** [grafana/xk6-disruptor#251]
This epic collects issues for improving the fault injection API

General

- [ ] https://github.com/grafana/xk6-disruptor/issues/223
- [ ] https://github.com/grafana/xk6-disruptor/issues/247
- [ ] https://github.com/grafana/xk6-disruptor/issues/250
 
Fault Injection
- [ ] https://github.com/grafana/xk6-disruptor/issues/73
- [ ]  https://github.com/grafana/xk6-disruptor/issues/185
- [ ] https://github.com/grafana/xk6-disruptor/issues/186
- [ ] https://github.com/grafana/xk6-disruptor/issues/195
- [ ] https://github.com/grafana/xk6-disruptor/issues/196
- [ ] https://github.com/grafana/xk6-disruptor/issues/200
- [ ] https://github.com/grafana/xk6-disruptor/issues/245
